dist: xenial
branches:
  only:
    - master
language: csharp
solution: ServiceAppointmentPlugin.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build ServiceAppointmentPlugin.sln
  - dotnet test -v n ServiceAppointmentPlugin.Integration.Test/ServiceAppointmentPlugin.Integration.Test.csproj
